### ISSUE TITLE
fingerprints in docker are different every time

### ISSUE THREAD

**Issue by nschloe** [keygen-sh/py-machineid#18]
Running
```
docker run python:3.11.6 /bin/bash -c "pip install py-machineid==0.4.5 && python -c 'import machineid; print(machineid.id())'"
```
gives a new finterprint every time. This is via the `grep -oP '(?<=docker/containers/)([a-f0-9]+)(?=/hostname)' /proc/self/mountinfo"` branch which fetches the `fbc2...` part in 
```
393 324 254:0 /var/lib/docker/containers/fbc23b5cadda6cc86786c04341c95a19b3b9b6504d044b5a9e1bd928d37deb36/resolv.conf /etc/resolv.conf rw,noatime - ext4 /dev/mapper/luks-cc82adab-c4a4-4dec-975c-e9824aa35958 rw
```
Machine-locking makes little sense this way. Is it possible to get the fp of the host machine perhaps?

**Comment by ezekg** [comment]
At first I thought this was another variation of https://github.com/keygen-sh/py-machineid/issues/4 (Docker changing the internal `mountinfo` format), but upon re-reading — this is expected behavior, as far as I understand. You're running a new container every time you run that command… so the fingerprint will always be different… because it's a different container every time.

The Docker container has no access to the underlying physical hardware, so if you want to lock to the actual hardware and not the container, you will need [to pass the physical identifier into the Docker environment](https://stackoverflow.com/questions/48643360/passing-unique-hardware-identifier-to-docker-container).

When node-locking a virtual machine or container, you need to do things a bit differently. You should utilize machine and process heartbeats to manage concurrency, and you should expect machines to be short-lived and deactivate them upon container exit, while the heartbeat system culls crashed containers.

Docs: https://keygen.sh/docs/choosing-a-licensing-model/floating-licenses/#licensing-virtual-machines
