### ISSUE TITLE
Fails to obtain a machine ID for Gitlab CI runners

### ISSUE THREAD

**Issue by bjmc** [keygen-sh/py-machineid#19]
Exceptions is:

```
/usr/local/lib/python3.10/dist-packages/machineid/__init__.py:102: in id
    raise Exception('failed to obtain id on platform {}'.format(platform))
E   Exception: failed to obtain id on platform linux
```

 ([detail here](https://gitlab.com/ska-telescope/ska-ser-skuid/-/jobs/7021703814))
 
 Any suggestions? I'm assuming it runs in some kind of virtualized environment, so I'm not even sure what would make sense. Can we retrieve a container ID or similar?

**Comment by bjmc** [comment]
According to [the docs](https://docs.gitlab.com/ee/ci/variables/predefined_variables.html) there is an environment variable `CI_RUNNER_ID` "The unique ID of the runner being used." that sounds appropriate, but I'm not sure about the wisdom of special-casing for one vendor.

**Comment by ezekg** [comment]
These [are all the locations we check on Linux](https://github.com/keygen-sh/py-machineid/blob/master/machineid/__init__.py#L82-L95). If GitLab or another CI runner locks down these files, or otherwise makes them inaccessible, we'll be unable to determine the device ID. I'm not really interested in adding workarounds for specific CI runners, so instead I'd recommend trying to write a UUID or even `CI_RUNNER_ID` to one of those locations, namely `/var/lib/dbus/machine-id` or `/etc/machine-id`, when setting up your test suite and see if that works.
